# マクロ（定数）の定義
CC = gcc
CFLAGS = -Wall -g
.PHONY: all clean	# ダミーターゲットを明示的に指定

# makeの引数なしで生成するものの一覧
all: printAddr1 pointerAccess swapVar1 nullPointer loopFuncBig bubbleSort1 printAddr3 pointerScanf swapVar2 shoppingPtr bubbleSort2


# コンパイルによってできるものを削除する
clean:
	rm -f *.o printAddr1 pointerAccess swapVar1 nullPointer loopFuncBig bubbleSort1 printAddr2 printAddr3 printAddr4 pointerScanf swapVar2 shoppingPtr bubbleSort2
	rm -rf *.dSYM
