( echo 3; echo 1; echo 2 ) | python3 max.py
( echo 3; echo 2; echo 1 ) | python3 max.py
( echo 1; echo 3; echo 2 ) | python3 max.py
( echo 2; echo 3; echo 1 ) | python3 max.py
( echo 1; echo 2; echo 3 ) | python3 max.py
( echo 2; echo 1; echo 3 ) | python3 max.py
( echo 3; echo 1; echo 1 ) | python3 max.py
( echo 1; echo 3; echo 1 ) | python3 max.py
( echo 1; echo 1; echo 3 ) | python3 max.py
( echo 3; echo 3; echo 1 ) | python3 max.py
( echo 3; echo 1; echo 3 ) | python3 max.py
( echo 1; echo 3; echo 3 ) | python3 max.py
( echo 3; echo 3; echo 3 ) | python3 max.py
